name: Dev Branch CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4

    - name: Copy application.yml
      run: |
        echo "${{ secrets.APPLICATION_YML }}" >> src/main/resources/application.yml

    - name: Build JAR with Gradle
      run: ./gradlew clean build

    - name: Build Docker Image
      run: |
        docker build -t my-app:latest .

    - name: Login to DockerHub
      run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

    - name: Tag and Push Docker Image
      run: |
        docker tag my-app:latest ${{ secrets.DOCKERHUB_USERNAME }}/my-app:latest
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/my-app:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: SSH into EC2 and Deploy
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          docker stop my-app-container || true
          docker rm my-app-container || true
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/my-app:latest
          docker run -d --name my-app-container -p 8080:8080 ${{ secrets.DOCKERHUB_USERNAME }}/my-app:latest
