name: Dev Branch CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4

    - name: Copy application.yml to backend
      run: echo "${{ secrets.APPLICATION_YML }}" > backend/application.yml

    - name: Build JAR with Gradle
      run: ./gradlew bootJar
      working-directory: backend

    - name: Build Docker Image
      run: docker build -t onu:latest .
      working-directory: backend

    - name: Login to DockerHub
      run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

    - name: Tag and Push Docker Image
      run: |
        docker tag onu:latest ${{ secrets.DOCKERHUB_USERNAME }}/onu:latest
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/onu:latest
